# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'

puts 'cleaning database'
Book.destroy_all
puts 'creating your library of books'


category = ['sociology', 'history', 'economy', 'business', 'investing', 'trading']
books_attributes = [
  ############################## Sociology ##############################################
  {
    title:        'Principles of Economic Sociology',
    description:  "The last fifteen years have witnessed an explosion in the popularity, creativity, and productiveness of economic sociology, an approach that traces its roots back to Max Weber. This important new text offers a comprehensive and up-to-date overview of economic sociology. It also advances the field theoretically by highlighting, in one analysis, the crucial economic roles of both interests and social relations. Richard Swedberg describes the field's critical insights into economic life, giving particular attention to the effects of culture on economic phenomena and the ways that economic actions are embedded in social structures. He examines the full range of economic institutions and explicates the relationship of the economy to politics, law, culture, and gender. Swedberg notes that sociologists too often fail to properly emphasize the role that self-interested behavior plays in economic decisions, while economists frequently underestimate the importance of social relations. Thus, he argues that the next major task for economic sociology is to develop a theoretical and empirical understanding of how interests and social relations work in combination to affect economic action. Written by an author whose name is synonymous with economic sociology, this text constitutes a sorely needed advanced synthesis--and a blueprint for the future of this burgeoning field." ,
    category:     "sociology",
    link:         'https://www.amazon.ca/Principles-Economic-Sociology-Richard-Swedberg/dp/0691130590/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1592509407&sr=8-1',
    photo:        "principles of economic sociology.jpg"
  },
  {
    title:        'Economy and Society: A new Translation by Max Weber' ,
    description:  'Max Weber’s Economy and Society is the foundational text for the social sciences of the twentieth and twenty-first centuries, presenting a framework for understanding the relations among individual action, social action, economic action, and economic institutions. It also provides a classification of political forms based upon “systems of rule” and “rulership” that has shaped debate about the nature and role of charisma, tradition, legal authority, and bureaucracy. Keith Tribe’s major new translation presents Economy and Society as it stood when Weber died in June 1920, with three complete chapters and a fragment of a fourth. One of the English-speaking world’s leading experts on Weber’s thought, Tribe has produced a uniquely clear and faithful translation that balances accuracy with readability. He adds to this a substantial introduction and commentary that reflect the new Weber scholarship of the past few decades. This new edition will become the definitive translation of one of the few indisputably great intellectual works of the past 150 years.' ,
    category:     'sociology',
    link:         'https://www.amazon.ca/Economy-Society-Translation-Max-Weber/dp/0674916549/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1592510015&sr=8-1',
    photo:        "economy and society.jpg"
  },
  {
    title:        'The Architecture Of Markets' ,
    description:  'Market societies have created more wealth, and more opportunities for more people, than any other system of social organization in history. Yet we still have a rudimentary understanding of how markets themselves are social constructions that require extensive institutional support. This groundbreaking work seeks to fill this gap, to make sense of modern capitalism by developing a sociological theory of market institutions. Addressing the unruly dynamism that capitalism brings with it, leading sociologist Neil Fligstein argues that the basic drift of any one market and its actors, even allowing for competition, is toward stabilization. The Architecture of Markets represents a major and timely step beyond recent, largely empirical studies that oppose the neoclassical model of perfect competition but provide sparse theory toward a coherent economic sociology. Fligstein offers this theory. With it he interprets not just globalization and the information economy, but developments more specific to American capitalism in the past two decades--among them, the 1980s merger movement. He makes new inroads into the ''theory of fields,'' which links the formation of markets and firms to the problems of stability. His political-cultural approach explains why governments remain crucial to markets and why so many national variations of capitalism endure. States help make stable markets possible by, for example, establishing the rule of law and adjudicating the class struggle. State-building and market-building go hand in hand. Fligstein shows that market actors depend mightily upon governments and the members of society for the social conditions that produce wealth. He demonstrates that systems favoring more social justice and redistribution can yield stable markets and economic growth as readily as less egalitarian systems. This book will surely join the classics on capitalism. Economists, sociologists, policymakers, and all those interested in what makes markets function as they do will read it for many years to come.' ,
    category:     'sociology',
    link:         'https://www.amazon.ca/Architecture-Markets-Sociology-Twenty-First-Century-Capitalist/dp/0691102546/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1592510274&sr=8-3',
    photo:        "the architecture of markets.jpg"
  },
  {
    title:        'The Handbook Of Economic Sociology',
    description:  'The Handbook of Economic Sociology, Second Edition is the most comprehensive and up-to-date treatment of economic sociology available. The first edition, copublished in 1994 by Princeton University Press and the Russell Sage Foundation as a synthesis of the burgeoning field of economic sociology, soon established itself as the definitive presentation of the field, and has been widely read, reviewed, and adopted. Since then, the field of economic sociology has continued to grow by leaps and bounds and to move into new theoretical and empirical territory. The second edition, while being as all-embracing in its coverage as the first edition, represents a wholesale revamping. Neil Smelser and Richard Swedberg have kept the main overall framework intact, but nearly two-thirds of the chapters are new or have new authors. As in the first edition, they bring together leading sociologists as well as representatives of other social sciences. But the thirty chapters of this volume incorporate many substantial thematic changes and new lines of research--for example, more focus on international and global concerns, chapters on institutional analysis, the transition from socialist economies, organization and networks, and the economic sociology of the ancient world. The Handbook of Economic Sociology, Second Edition is the definitive resource on what continues to be one of the leading edges of sociology and one of its most important interdisciplinary adventures. It is a must read for all faculty, graduate students, and undergraduates doing work in the field.',
    category:     'sociology',
    link:         'https://www.amazon.ca/Handbook-Economic-Sociology-Second/dp/0691121265/ref=sr_1_1?dchild=1&keywords=the+handbook+of+economic+sociology&qid=1592510542&s=digital-skills&sr=1-1',
    photo:        "the handbook of economic sociology.jpg"
  },
  {
    title:        'The Sociology of Economic Life',
    description:  "This book incorporates classic and contemporary readings in economic sociology and related disciplines to provide students with a broad understanding of the many dimensions of economic life. It discusses Max Weber's key concepts in economics and sociology." ,
    category:     'sociology',
    link:         'https://www.amazon.ca/Sociology-Economic-Life-Mark-Granovetter/dp/0813344557/ref=sr_1_1?dchild=1&keywords=the+sociology+of+economics+life&qid=1592510726&s=digital-skills&sr=1-1',
    photo:        "The Sociology of Economic Life.jpg"
  },
  {
    title:        'Economic Sociology: A Systematic Inquiry',
    description:  "The sociological study of economic activity has witnessed a significant resurgence. Recent texts have chronicled economic sociology's nineteenth-century origins while pointing to the importance of context and power in economic life, yet the field lacks a clear understanding of the role that concepts at different levels of abstraction play in its organization. Economic Sociology fills this critical gap by surveying the current state of the field while advancing a framework for further theoretical development. Alejandro Portes examines economic sociology's principal assumptions, key explanatory concepts, and selected research sites. He argues that economic activity is embedded in social and cultural relations, but also that power and the unintended consequences of rational purposive action must be factored in when seeking to explain or predict economic behavior. Drawing upon a wealth of examples, Portes identifies three strategic sites of research--the informal economy, ethnic enclaves, and transnational communities--and he eschews grand narratives in favor of mid-range theories that help us understand specific kinds of social action. The book shows how the meta-assumptions of economic sociology can be transformed, under certain conditions, into testable propositions, and puts forward a theoretical agenda aimed at moving the field out of its present impasse.",
    category:     'sociology',
    link:         "https://www.amazon.ca/Economic-Sociology-Systematic-Alejandro-Portes/dp/0691142238/ref=sr_1_1?dchild=1&keywords=Economic+Sociology%3A+A+Systematic+Inquiry&qid=1592510932&sr=8-1",
    photo:        "economic sociology a systematic inquiry.jpg"
  },
  {
    title:        'The Economic Sociology of Capitalism',
    description:  "This book represents a major step forward in the use of economic sociology to illuminate the nature and workings of capitalism amid the far-reaching changes of the contemporary era of global capitalism. For the past twenty years economic sociologists have focused on mesa-level phenomena of networks, but they have done relatively little to analyze capitalism as an overall system or to show how such phenomena emerge from and shape the dynamics of capitalism. The Economic Sociology of Capitalism seeks to change this, by presenting both big-picture analyses of capitalism and more focused pieces on institutions crucial to capitalism. The book, which includes sixteen chapters by leading scholars in economic sociology, is organized around three broad themes. The first section addresses core issues and problems in the new study of capitalism; the second considers a variety of topics concerning America, the leading capitalist economy of the world; and the third focuses attention on the question of convergence stemming from the global transformation of capitalism and the challenge of explaining institutional change. The contributions, which follow a foreword by economic historian Avner Greif and the editor's introduction, are by Mitchel Abolafia, James Baron and Michael Hannan, Mary C. Brinton, John Campbell, Gerald Davis and Christopher Marquis, Paul DiMaggio and Joseph Cohen, Peter Evans, Neil Fligstein, John Freeman, Francis Fukuyama, Ko Kuwabara, Victor Nee, Douglass C. North, AnnaLee Saxenian, Richard Swedberg, and Viviana Zelizer.",
    category:     'sociology',
    link:         'https://www.amazon.ca/Economic-Sociology-Capitalism-Victor-Nee/dp/0691119589/ref=sr_1_1?dchild=1&keywords=The+Economic+Sociology+of+Capitalism&qid=1592511394&s=digital-skills&sr=1-1',
    photo:        "The Economic Sociology of Capitalism.jpg"
  },
  ##################### History ################################
  {
    title:        'History of economic thought',
    description:  'An upper-level text, History of Economic Thought continues to offer a lively, accessible discussion of ideas that have shaped modern economics. The Fourth Edition has been thoroughly revised to reflect recent scholarship and research, as well as a more pointed focus on modern economic thought. The text remains a highly understandable and opinionated?but fair?presentation of the history of economic thought.',
    category:     'history',
    link:         'https://www.amazon.ca/History-Economic-Thought-Harry-Landreth/dp/0618133941/ref=sr_1_1?dchild=1&keywords=history+of+economic+thought+landreth&qid=1592511812&sr=8-1',
    photo:        "History of economic thought.jpg"
  },
  {
    title:        'A Farewell to Alms',
    description:  "Why are some parts of the world so rich and others so poor? Why did the Industrial Revolution--and the unprecedented economic growth that came with it--occur in eighteenth-century England, and not at some other time, or in some other place? Why didn't industrialization make the whole world rich--and why did it make large parts of the world even poorer? In A Farewell to Alms, Gregory Clark tackles these profound questions and suggests a new and provocative way in which culture--not exploitation, geography, or resources--explains the wealth, and the poverty, of nations. Countering the prevailing theory that the Industrial Revolution was sparked by the sudden development of stable political, legal, and economic institutions in seventeenth-century Europe, Clark shows that such institutions existed long before industrialization. He argues instead that these institutions gradually led to deep cultural changes by encouraging people to abandon hunter-gatherer instincts-violence, impatience, and economy of effort-and adopt economic habits-hard work, rationality, and education. The problem, Clark says, is that only societies that have long histories of settlement and security seem to develop the cultural characteristics and effective workforces that enable economic growth. For the many societies that have not enjoyed long periods of stability, industrialization has not been a blessing. Clark also dissects the notion, championed by Jared Diamond in Guns, Germs, and Steel, that natural endowments such as geography account for differences in the wealth of nations. A brilliant and sobering challenge to the idea that poor societies can be economically developed through outside intervention, A Farewell to Alms may change the way global economic history is understood.",
    category:     'history',
    link:         'https://www.amazon.ca/Farewell-Alms-Brief-Economic-History/dp/0691141282/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1592511903&sr=8-1',
    photo:        "A Farewell to Alms.jpg"
  },
  {
    title:        'Global Economic History',
    description:  "What are the problems addressed by the growing field of global economic history? What debates and methodologies does it engage with? As Global Economic History shows, there are many answers to these questions. Riello and Roy, alongside 20 leading academics from the US, UK, Europe, Australia and Japan, explain why a global perspective matters to economic history. The impressive cast recruited by the editors brings together top scholars in their respective areas of expertise, including John McNeill, Patrick O'Brien, and Prasannan Parthasarathi. An ambitious scope of topics ranges from the 'Great Divergence' to the rise of global finance, to the New World and the global silver economy. Chapters are organized both thematically (Divergence in Global History and Emergence of a World Economy), and geographically (Regional Perspectives on Global Economic Change), ensuring the global perspective required on these challenging courses today. The result is a textbook which provides students with a quick and confident grasp of the field and its essential issues.",
    category:     'history',
    link:         'https://www.amazon.ca/Global-Economic-History-Tirthankar-Roy/dp/1472588428/ref=sr_1_2?dchild=1&keywords=Global+Economic+History&qid=1592512012&sr=8-2',
    photo:        "Global Economic History.jpg"
  },
  {
    title:        'Why Nations Fail',
    description:  "Is it culture, the weather, geography? Perhaps ignorance of what the right policies are? Simply, no. None of these factors is either definitive or destiny. Otherwise, how to explain why Botswana has become one of the fastest growing countries in the world, while other African nations, such as Zimbabwe, the Congo, and Sierra Leone, are mired in poverty and violence? Daron Acemoglu and James Robinson conclusively show that it is man-made political and economic institutions that underlie economic success (or lack of it). Korea, to take just one of their fascinating examples, is a remarkably homogeneous nation, yet the people of North Korea are among the poorest on earth while their brothers and sisters in South Korea are among the richest. The south forged a society that created incentives, rewarded innovation, and allowed everyone to participate in economic opportunities. The economic success thus spurred was sustained because the government became accountable and responsive to citizens and the great mass of people. Sadly, the people of the north have endured decades of famine, political repression, and very different economic institutions—with no end in sight. The differences between the Koreas is due to the politics that created these completely different institutional trajectories. Based on fifteen years of original research Acemoglu and Robinson marshall extraordinary historical evidence from the Roman Empire, the Mayan city-states, medieval Venice, the Soviet Union, Latin America, England, Europe, the United States, and Africa to build a new theory of political economy with great relevance for the big questions of today.",
    category:     'history',
    link:         'https://www.amazon.ca/Why-Nations-Fail-Origins-Prosperity/dp/0307719219/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592512262&sr=1-1',
    photo:        "Why Nations Fail.jpg"
  },
  {
    title:        'Capital in the Twenty-First Century',
    description:  "What are the grand dynamics that drive the accumulation and distribution of capital? Questions about the long-term evolution of inequality, the concentration of wealth, and the prospects for economic growth lie at the heart of political economy. But satisfactory answers have been hard to find for lack of adequate data and clear guiding theories. In Capital in the Twenty-First Century, Thomas Piketty analyzes a unique collection of data from twenty countries, ranging as far back as the eighteenth century, to uncover key economic and social patterns. His findings will transform debate and set the agenda for the next generation of thought about wealth and inequality. Piketty shows that modern economic growth and the diffusion of knowledge have allowed us to avoid inequalities on the apocalyptic scale predicted by Karl Marx. But we have not modified the deep structures of capital and inequality as much as we thought in the optimistic decades following World War II. The main driver of inequality―the tendency of returns on capital to exceed the rate of economic growth―today threatens to generate extreme inequalities that stir discontent and undermine democratic values. But economic trends are not acts of God. Political action has curbed dangerous inequalities in the past, Piketty says, and may do so again. A work of extraordinary ambition, originality, and rigor, Capital in the Twenty-First Century reorients our understanding of economic history and confronts us with sobering lessons for today.",
    category:     'history',
    link:         'https://www.amazon.ca/Capital-Twenty-First-Century-Thomas-Piketty/dp/067443000X/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592512443&sr=1-1',
    photo:        "Capital in the Twenty-First Century.jpg"
  },
  {
    title:        'The Great Divergence: China, Europe, and the Making of the Modern World Economy',
    description:  "The Great Divergence brings new insight to one of the classic questions of history: Why did sustained industrial growth begin in Northwest Europe, despite surprising similarities between advanced areas of Europe and East Asia? As Ken Pomeranz shows, as recently as 1750, parallels between these two parts of the world were very high in life expectancy, consumption, product and factor markets, and the strategies of households. Perhaps most surprisingly, Pomeranz demonstrates that the Chinese and Japanese cores were no worse off ecologically than Western Europe. Core areas throughout the eighteenth-century Old World faced comparable local shortages of land-intensive products, shortages that were only partly resolved by trade. Pomeranz argues that Europe's nineteenth-century divergence from the Old World owes much to the fortunate location of coal, which substituted for timber. This made Europe's failure to use its land intensively much less of a problem, while allowing growth in energy-intensive industries. Another crucial difference that he notes has to do with trade. Fortuitous global conjunctures made the Americas a greater source of needed primary products for Europe than any Asian periphery. This allowed Northwest Europe to grow dramatically in population, specialize further in manufactures, and remove labor from the land, using increased imports rather than maximizing yields. Together, coal and the New World allowed Europe to grow along resource-intensive, labor-saving paths. Meanwhile, Asia hit a cul-de-sac. Although the East Asian hinterlands boomed after 1750, both in population and in manufacturing, this growth prevented these peripheral regions from exporting vital resources to the cloth-producing Yangzi Delta. As a result, growth in the core of East Asia's economy essentially stopped, and what growth did exist was forced along labor-intensive, resource-saving paths--paths Europe could have been forced down, too, had it not been for favorable resource stocks from underground and overseas.",
    category:     'history',
    link:         'https://www.amazon.ca/Great-Divergence-Europe-Making-Economy/dp/0691090106/ref=sr_1_1?dchild=1&keywords=The+Great+Divergence&qid=1592512572&sr=8-1',
    photo:        "The Great Divergence.jpg"
  },
  {
    title:        'Power and Plenty: Trade, War, and the World Economy in the Second Millennium',
    description:  "International trade has shaped the modern world, yet until now no single book has been available for both economists and general readers that traces the history of the international economy from its earliest beginnings to the present day. Power and Plenty fills this gap, providing the first full account of world trade and development over the course of the last millennium. Ronald Findlay and Kevin O'Rourke examine the successive waves of globalization and 'deglobalization' that have occurred during the past thousand years, looking closely at the technological and political causes behind these long-term trends. They show how the expansion and contraction of the world economy has been directly tied to the two-way interplay of trade and geopolitics, and how war and peace have been critical determinants of international trade over the very long run. The story they tell is sweeping in scope, one that links the emergence of the Western economies with economic and political developments throughout Eurasia centuries ago. Drawing extensively upon empirical evidence and informing their systematic analysis with insights from contemporary economic theory, Findlay and O'Rourke demonstrate the close interrelationships of trade and warfare, the mutual interdependence of the world's different regions, and the crucial role these factors have played in explaining modern economic growth.",
    category:     'history',
    link:         "https://www.amazon.ca/Power-Plenty-Economy-Second-Millennium/dp/0691143277/ref=sr_1_1?dchild=1&keywords=Power+and+Plenty%3A+Trade%2C+War%2C+and+the+World+Economy+in+the+Second+Millennium&qid=1592512684&sr=8-1",
    photo:        "Power and Plenty.jpg"
  },
  {
    title:        'The Ascent of Money: A Financial History of the World',
    description:  "Niall Ferguson follows the money to tell the human story behind the evolution of finance, from its origins in ancient Mesopotamia to the latest upheavals on what he calls Planet Finance. Bread, cash, dosh, dough, loot, lucre, moolah, readies, the wherewithal: Call it what you like, it matters. To Christians, love of it is the root of all evil. To generals, it’s the sinews of war. To revolutionaries, it’s the chains of labor. But in The Ascent of Money, Niall Ferguson shows that finance is in fact the foundation of human progress. What’s more, he reveals financial history as the essential backstory behind all history. Through Ferguson’s expert lens familiar historical landmarks appear in a new and sharper financial focus. Suddenly, the civilization of the Renaissance looks very different: a boom in the market for art and architecture made possible when Italian bankers adopted Arabic mathematics. The rise of the Dutch republic is reinterpreted as the triumph of the world’s first modern bond market over insolvent Habsburg absolutism. And the origins of the French Revolution are traced back to a stock market bubble caused by a convicted Scot murderer. With the clarity and verve for which he is known, Ferguson elucidates key financial institutions and concepts by showing where they came from. What is money? What do banks do? What’s the difference between a stock and a bond? Why buy insurance or real estate? And what exactly does a hedge fund do? This is history for the present. Ferguson travels to post-Katrina New Orleans to ask why the free market can’t provide adequate protection against catastrophe. He delves into the origins of the subprime mortgage crisis. Perhaps most important, The Ascent of Money documents how a new financial revolution is propelling the world’s biggest countries, India and China, from poverty to wealth in the space of a single generation—an economic transformation unprecedented in human history. Yet the central lesson of the financial history is that sooner or later every bubble bursts—sooner or later the bearish sellers outnumber the bullish buyers, sooner or later greed flips into fear. And that’s why, whether you’re scraping by or rolling in it, there’s never been a better time to understand the ascent of money.",
    category:     'history',
    link:         'https://www.amazon.ca/Ascent-Money-Financial-History-World/dp/1594201927/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592512785&sr=1-1',
    photo:        "The Ascent of Money.jpg"
  },
  {
    title:        'Lords of Finance: The Bankers Who Broke the World',
    description:  "It is commonly believed that the Great Depression that began in 1929 resulted from a confluence of events beyond any one person?s or government?s control. In fact, as Liaquat Ahamed reveals, it was the decisions taken by a small number of central bankers that were the primary cause of the economic meltdown, the effects of which set the stage for World War II and reverberated for decades. In Lords of Finance, we meet the neurotic and enigmatic Montagu Norman of the Bank of England, the xenophobic and suspicious Émile Moreau of the Banque de France, the arrogant yet brilliant Hjalmar Schacht of the Reichsbank, and Benjamin Strong of the Federal Reserve Bank of New York, whose façade of energy and drive masked a deeply wounded and overburdened man. After the First World War, these central bankers attempted to reconstruct the world of international finance. Despite their differences, they were united by a common fear?that the greatest threat to capitalism was inflation? and by a common vision that the solution was to turn back the clock and return the world to the gold standard. For a brief period in the mid-1920s they appeared to have succeeded. The world?s currencies were stabilized and capital began flowing freely across the globe. But beneath the veneer of boom-town prosperity, cracks started to appear in the financial system. The gold standard that all had believed would provide an umbrella of stability proved to be a straitjacket, and the world economy began that terrible downward spiral known as the Great Depression. As yet another period of economic turmoil makes headlines today, the Great Depression and the year 1929 remain the benchmark for true financial mayhem. Offering a new understanding of the global nature of financial crises, Lords of Finance is a potent reminder of the enormous impact that the decisions of central bankers can have, of their fallibility, and of the terrible human consequences that can result when they are wrong.",
    category:     'history',
    link:         'https://www.amazon.ca/Liaquat-Ahamed/dp/159420182X/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592512975&sr=1-1',
    photo:        "Lords of Finance.jpg"
  },
  {
    title:        'Guns, Germs, and Steel',
    description:  "Winner of the Pulitzer Prize, Guns, Germs, and Steel is a brilliant work answering the question of why the peoples of certain continents succeeded in invading other continents and conquering or displacing their peoples. This edition includes a new chapter on Japan and all-new illustrations drawn from the television series. Until around 11,000 BC, all peoples were still Stone Age hunter/gatherers. At that point, a great divide occurred in the rates that human societies evolved. In Eurasia, parts of the Americas, and Africa, farming became the prevailing mode of existence when indigenous wild plants and animals were domesticated by prehistoric planters and herders. As Jared Diamond vividly reveals, the very people who gained a head start in producing food would collide with preliterate cultures, shaping the modern world through conquest, displacement, and genocide.The paths that lead from scattered centers of food to broad bands of settlement had a great deal to do with climate and geography. But how did differences in societies arise? Why weren't native Australians, Americans, or Africans the ones to colonize Europe? Diamond dismantles pernicious racial theories tracing societal differences to biological differences. He assembles convincing evidence linking germs to domestication of animals, germs that Eurasians then spread in epidemic proportions in their voyages of discovery. In its sweep, Guns, Germs and Steel encompasses the rise of agriculture, technology, writing, government, and religion, providing a unifying theory of human history as intriguing as the histories of dinosaurs and glaciers.",
    category:     'history',
    link:         'https://www.amazon.ca/Guns-Germs-Steel-Human-Societies/dp/0393061310/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592513127&sr=8-1',
    photo:        "Guns, Germs, and Steel.jpg"
  },
  {
    title:        'Capitalism in America: A History',
    description:  "From even the start of his fabled career, Alan Greenspan was duly famous for his deep understanding of even the most arcane corners of the American economy, and his restless curiosity to know even more. To the extent possible, he has made a science of understanding how the US economy works almost as a living organism--how it grows and changes, surges and stalls. He has made a particular study of the question of productivity growth, at the heart of which is the riddle of innovation. Where does innovation come from, and how does it spread through a society? And why do some eras see the fruits of innovation spread more democratically, and others, including our own, see the opposite? In Capitalism in America, Greenspan distills a lifetime of grappling with these questions into a thrilling and profound master reckoning with the decisive drivers of the US economy over the course of its history. In partnership with the celebrated Economist journalist and historian Adrian Wooldridge, he unfolds a tale involving vast landscapes, titanic figures, triumphant breakthroughs, enlightenment ideals as well as terrible moral failings. Every crucial debate is here--from the role of slavery in the antebellum Southern economy to the real impact of FDR's New Deal to America's violent mood swings in its openness to global trade and its impact. But to read Capitalism in America is above all to be stirred deeply by the extraordinary productive energies unleashed by millions of ordinary Americans that have driven this country to unprecedented heights of power and prosperity. At heart, the authors argue, America's genius has been its unique tolerance for the effects of creative destruction, the ceaseless churn of the old giving way to the new, driven by new people and new ideas. Often messy and painful, creative destruction has also lifted almost all Americans to standards of living unimaginable to even the wealthiest citizens of the world a few generations past. A sense of justice and human decency demands that those who bear the brunt of the pain of change be protected, but America has always accepted more pain for more gain, and its vaunted rise cannot otherwise be understood, or its challenges faced, without recognizing this legacy. For now, in our time, productivity growth has stalled again, stirring up the populist furies. There's no better moment to apply the lessons of history to the most pressing question we face, that of whether the United States will preserve its preeminence, or see its leadership pass to other, inevitably less democratic powers.",
    category:     'history',
    link:         'https://www.amazon.ca/dp/0735222444?psc=1&th=1&ascsubtag=4686729|n1cfb33b8ad7542f8b542b9e40f27002120&linkCode=gs2&tag=dotdashca-20',
    photo:        "Capitalism in America.jpg"
  },
  ################################### Economy ##########################################################
  {
    title:        'Economics in One Lesson: The Shortest and Surest Way to Understand Basic Economics',
    description:  "Considered among the leading economic thinkers of the “Austrian School,” which includes Carl Menger, Ludwig von Mises, Friedrich (F.A.) Hayek, and others, Henry Hazlitt (1894-1993), was a libertarian philosopher, an economist, and a journalist. He was the founding vice-president of the Foundation for Economic Education and an early editor of The Freeman magazine, an influential libertarian publication.  Hazlitt wrote Economics in One Lesson, his seminal work, in 1946. Concise and instructive, it is also deceptively prescient and far-reaching in its efforts to dissemble economic fallacies that are so prevalent they have almost become a new orthodoxy. Many current economic commentators across the political spectrum have credited Hazlitt with foreseeing the collapse of the global economy which occurred more than 50 years after the initial publication of Economics in One Lesson. Hazlitt’s focus on non-governmental solutions, strong — and strongly reasoned — anti-deficit position, and general emphasis on free markets, economic liberty of individuals, and the dangers of government intervention make Economics in One Lesson, every bit as relevant and valuable today as it has been since publication.",
    category:     'economy',
    link:         'https://www.amazon.ca/dp/0517548232?psc=1&th=1&ascsubtag=4686729|n1cfb33b8ad7542f8b542b9e40f27002120&linkCode=gs2&tag=dotdashca-20',
    photo:        "Economics in One Lesson.jpg"
  },
  {
    title:        "Basic Economics",
    description:  "Basic Economics is a citizen's guide to economics, written for those who want to understand how the economy works but have no interest in jargon or equations. Bestselling economist Thomas Sowell explains the general principles underlying different economic systems: capitalist, socialist, feudal, and so on. In readable language, he shows how to critique economic policies in terms of the incentives they create, rather than the goals they proclaim. With clear explanations of the entire field, from rent control and the rise and fall of businesses to the international balance of payments, this is the first book for anyone who wishes to understand how the economy functions. This fifth edition includes a new chapter explaining the reasons for large differences of wealth and income between nations. Drawing on lively examples from around the world and from centuries of history, Sowell explains basic economic principles for the general public in plain English.",
    category:     'economy',
    link:         'https://www.amazon.ca/Basic-Economics-Thomas-Sowell/dp/0465060730/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=',
    photo:        "Basic Economics.jpg"
  },
  {
    title:        'Freakonomics: A Rogue Economist Explores the Hidden Side of Everything',
    description:  "In the summer of 2003,The New York Times Magazinesent Stephen J. Dubner, an author and journalist, to write a profile of Steven D. Levitt, a heralded young economist at the University of Chicago. Levitt was not remotely interested in the things that interest most economists. Instead, he studied the riddles of everyday life-from cheating to crime to child-rearing-and his conclusions turned the conventional wisdom on its head. Levitt and Dubner then collaborated onFreakonomics, a book that gives full play to Levitt's most compelling ideas. Through forceful storytelling and sharp insight, it reminds us all that economics is, at its root, the study of incentives-how people get what they want or need, especially when other people want or need the same thing. Among the questions it answers: Which is more dangerous, a gun or a swimming pool? If drug dealers make so much money, why do they still live with their mothers? What makes a perfect parent? And, of course: What do schoolteachers and sumo wrestlers have in common? (Answer: they both cheat.) Now this cultural blockbuster comes to trade paperback with exclusive extras- including a new preface, five Freakonomics columns fromThe New York Times Magazine, an exclusive author Q & A and a sneak preview ofSuperfreakonomics.",
    category:     'economy',
    link:         'https://www.amazon.ca/Freakonomics-Economist-Explores-Hidden-Everything/dp/1554686369/ref=sr_1_1?crid=36O06Z9X6M84Z&dchild=1&keywords=freakonomics&qid=1592514000&s=books&sprefix=freak%2Caps%2C163&sr=1-1',
    photo:        "Freakonomics.jpg"
  },
  {
    title:        'Capitalism and Freedom: Fortieth',
    description:  "How can we benefit from the promise of government while avoiding the threat it poses to individual freedom? In this classic book, Milton Friedman provides the definitive statement of his immensely influential economic philosophy—one in which competitive capitalism serves as both a device for achieving economic freedom and a necessary condition for political freedom. The result is an accessible text that has sold well over half a million copies in English, has been translated into eighteen languages, and shows every sign of becoming more and more influential as time goes on.",
    category:     'economy',
    link:         'https://www.amazon.ca/dp/0226264211?psc=1&th=1&ascsubtag=4686729|n1cfb33b8ad7542f8b542b9e40f27002120&linkCode=gs2&tag=dotdashca-20',
    photo:        "Capitalism and Freedom.jpg"
  },
  {
    title:        'Doughnut Economics: Seven Ways to Think Like a 21st-Century Economist',
    description:  "Economics is the mother tongue of public policy. It dominates our decision-making for the future, guides multi-billion-dollar investments, and shapes our responses to climate change, inequality, and other environmental and social challenges that define our times. Pity then, or more like disaster, that its fundamental ideas are centuries out of date yet are still taught in college courses worldwide and still used to address critical issues in government and business alike. That’s why it is time, says renegade economist Kate Raworth, to revise our economic thinking for the 21st century. In Doughnut Economics, she sets out seven key ways to fundamentally reframe our understanding of what economics is and does. Along the way, she points out how we can break our addiction to growth; redesign money, finance, and business to be in service to people; and create economies that are regenerative and distributive by design. Named after the now-iconic “doughnut” image that Raworth first drew to depict a sweet spot of human prosperity (an image that appealed to the Occupy Movement, the United Nations, eco-activists, and business leaders alike), Doughnut Economics offers a radically new compass for guiding global development, government policy, and corporate strategy, and sets new standards for what economic success looks like. Raworth handpicks the best emergent ideas—from ecological, behavioral, feminist, and institutional economics to complexity thinking and Earth-systems science—to address this question: How can we turn economies that need to grow, whether or not they make us thrive, into economies that make us thrive, whether or not they grow? Simple, playful, and eloquent, Doughnut Economics offers game-changing analysis and inspiration for a new generation of economic thinkers.",
    category:     'economy',
    link:         'https://www.amazon.ca/dp/1603586741?psc=1&th=1&ascsubtag=4686729|n1cfb33b8ad7542f8b542b9e40f27002120&linkCode=gs2&tag=dotdashca-20',
    photo:        "Doughnut Economics.jpg"
  },
  {
    title:        'Thinking, Fast and Slow',
    description:  'In the international bestseller, Thinking, Fast and Slow, Daniel Kahneman, the renowned psychologist and winner of the Nobel Prize in Economics, takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think. System 1 is fast, intuitive, and emotional; System 2 is slower, more deliberative, and more logical. The impact of overconfidence on corporate strategies, the difficulties of predicting what will make us happy in the future, the profound effect of cognitive biases on everything from playing the stock market to planning our next vacation--each of these can be understood only by knowing how the two systems shape our judgments and decisions. Engaging the reader in a lively conversation about how we think, Kahneman reveals where we can and cannot trust our intuitions and how we can tap into the benefits of slow thinking. He offers practical and enlightening insights into how choices are made in both our business and our personal lives--and how we can use different techniques to guard against the mental glitches that often get us into trouble. Winner of the National Academy of Sciences Best Book Award and the Los Angeles Times Book Prize and selected by The New York Times Book Review as one of the ten best books of 2011, Thinking, Fast and Slow is destined to be a classic.',
    category:     'economy',
    link:         'https://www.amazon.ca/dp/0374533555?psc=1&th=1&ascsubtag=4686729|n1cfb33b8ad7542f8b542b9e40f27002120&linkCode=gs2&tag=dotdashca-20',
    photo:        "Thinking, Fast and Slow.jpg"
  },
  {
    title:        'The Economics Book: Big Ideas Simply Explained',
    description:  "The Economics Book is your plain-speaking, visual guide to these questions and beyond. Using a unique graphic approach, it explains the issues that affect us all, including taxation, recession, the housing market, the stock market, and savings rates. It highlights how economic ideas can shape our world, such as the need for nations to act collectively to solve issues, from migration to climate change. Using graphics and flow diagrams, The Economics Book demystifies and untangles complicated theories to make sense of abstract concepts. It also traces the history of economics from the ancient Greeks to today, presenting over 100 key ideas from the world's greatest economic thinkers, such as Thomas Malthus, John Maynard Keynes, and Milton Friedman, showing you how theories develop as one economist influenced the next. Whether you are studying economics or just want to know how the world really works, The Economics Book is both an accessible guide and an invaluable reference.",
    category:     'economy',
    link:         'https://www.amazon.ca/Economics-Book-Ideas-Simply-Explained/dp/0756698278/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592514773&sr=8-1',
    photo:        "The Economics Book.jpg"
  },
  ############################## Business ##############################################
  {
    title:        "Good to Great: Why Some Companies Make the Leap...and Others Don't",
    description:  "Built to Last, the defining management study of the nineties, showed how great companies triumph over time and how long-term sustained performance can be engineered into the DNA of an enterprise from the very beginning. But what about the company that is not born with great DNA? How can good companies, mediocre companies, even bad companies achieve enduring greatness? For years, this question preyed on the mind of Jim Collins. Are there companies that defy gravity and convert long-term mediocrity or worse into long-term superiority? And if so, what are the universal distinguishing characteristics that cause a company to go from good to great? Using tough benchmarks, Collins and his research team identified a set of elite companies that made the leap to great results and sustained those results for at least fifteen years. How great? After the leap, the good-to-great companies generated cumulative stock returns that beat the general stock market by an average of seven times in fifteen years, better than twice the results delivered by a composite index of the world's greatest companies, including Coca-Cola, Intel, General Electric, and Merck. The research team contrasted the good-to-great companies with a carefully selected set of comparison companies that failed to make the leap from good to great. What was different? Why did one set of companies become truly great performers while the other set remained only good? Over five years, the team analyzed the histories of all twenty-eight companies in the study. After sifting through mountains of data and thousands of pages of interviews, Collins and his crew discovered the key determinants of greatness -- why some companies make the leap and others don't.",
    category:     "business",
    link:         'amazon.ca',
    photo:        "Good to Great.jpg"
  },
  {
    title:        'The Lean Startup',
    description:  "Eric Ries defines a startup as an organization dedicated to creating something new under conditions of extreme uncertainty. This is just as true for one person in a garage or a group of seasoned professionals in a Fortune 500 boardroom. What they have in common is a mission to penetrate that fog of uncertainty to discover a successful path to a sustainable business. The Lean Startup approach fosters companies that are both more capital efficient and that leverage human creativity more effectively. Inspired by lessons from lean manufacturing, it relies on “validated learning,” rapid scientific experimentation, as well as a number of counter-intuitive practices that shorten product development cycles, measure actual progress without resorting to vanity metrics, and learn what customers really want. It enables a company to shift directions with agility, altering plans inch by inch, minute by minute. Rather than wasting time creating elaborate business plans, The Lean Startup offers entrepreneurs—in companies of all sizes—a way to test their vision continuously, to adapt and adjust before it’s too late. Ries provides a scientific approach to creating and managing successful startups in a age when companies need to innovate more than ever.",
    category:     'business',
    link:         'https://www.amazon.ca/Lean-Startup-Entrepreneurs-Continuous-Innovation/dp/0307887898/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592515350&sr=8-1',
    photo:        "The Lean Startup.jpg"
  },
  {
    title:        'Start With Why',
    description:  "In 2009, Simon Sinek started a movement to help people become more inspired at work, and in turn inspire their colleagues and customers. Since then, millions have been touched by the power of his ideas, including more than 28 million who’ve watched his TED Talk based on START WITH WHY -- the third most popular TED video of all time. Sinek starts with a fundamental question: Why are some people and organizations more innovative, more influential, and more profitable than others? Why do some command greater loyalty from customers and employees alike? Even among the successful, why are so few able to repeat their success over and over? People like Martin Luther King Jr., Steve Jobs, and the Wright Brothers had little in common, but they all started with WHY. They realized that people won't truly buy into a product, service, movement, or idea until they understand the WHY behind it. START WITH WHY shows that the leaders who've had the greatest influence in the world all think, act, and communicate the same way -- and it's the opposite of what everyone else does. Sinek calls this powerful idea The Golden Circle, and it provides a framework upon which organizations can be built, movements can be led, and people can be inspired. And it all starts with WHY.",
    category:     'business',
    link:         'https://www.amazon.ca/Start-Why-Leaders-Inspire-Everyone/dp/1591842808/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592515455&sr=8-1',
    photo:        "Start With Why.jpg"
  },
  {
    title:        'Shoe Dog: A Memoir by the Creator of Nike',
    description:  "In this candid and riveting memoir, for the first time ever, Nike founder and board chairman Phil Knight shares the inside story of the company’s early days as an intrepid start-up and its evolution into one of the world’s most iconic, game-changing, and profitable brands. Young, searching, fresh out of business school, Phil Knight borrowed fifty dollars from his father and launched a company with one simple mission: import high-quality, low-cost running shoes from Japan. Selling the shoes from the trunk of his Plymouth Valiant, Knight grossed eight thousand dollars that first year, 1963. Today, Nike’s annual sales top $30 billion. In this age of start-ups, Knight’s Nike is the gold standard, and its swoosh is more than a logo. A symbol of grace and greatness, it’s one of the few icons instantly recognized in every corner of the world. But Knight, the man behind the swoosh, has always been a mystery. Now, in a memoir that’s surprising, humble, unfiltered, funny, and beautifully crafted, he tells his story at last. It all begins with a classic crossroads moment. Twenty-four years old, backpacking through Asia and Europe and Africa, wrestling with life’s Great Questions, Knight decides the unconventional path is the only one for him. Rather than work for a big corporation, he will create something all his own, something new, dynamic, different. Knight details the many terrifying risks he encountered along the way, the crushing setbacks, the ruthless competitors, the countless doubters and haters and hostile bankers—as well as his many thrilling triumphs and narrow escapes. Above all, he recalls the foundational relationships that formed the heart and soul of Nike, with his former track coach, the irascible and charismatic Bill Bowerman, and with his first employees, a ragtag group of misfits and savants who quickly became a band of swoosh-crazed brothers. Together, harnessing the electrifying power of a bold vision and a shared belief in the redemptive, transformative power of sports, they created a brand, and a culture, that changed everything.",
    category:     'business',
    link:         'https://www.amazon.ca/Shoe-Dog-Memoir-Creator-Nike/dp/1501135910/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592515591&sr=8-1',
    photo:        "Shoe Dog.jpg"
  },
  {
    title:        'Built to Last : Successful Habits of Visionary Companies',
    description:  "'This is not a book about charismatic visionary leaders. It is not about visionary product concepts or visionary products or visionary market insights. Nor is it about just having a corporate vision. This is a book about something far more important, enduring, and substantial. This is a book about visionary companies'. So write Jim Collins and Jerry Porras in this groundbreaking book that shatters myths, provides new insights, and gives practical guidance to those who would like to build landmark companies that stand the test of time. Drawing upon a six-year research project at the Stanford University Graduate School of Business, Collins and Porras took eighteen truly exceptional and long-lasting companies -- they have an average age of nearly one hundred years and have outperformed the general stock market by a factor of fifteen since 1926 -- and studied each company in direct comparison to one of its top competitors. They examined the companies from their very beginnings to the present day -- as start-ups, as midsize companies, and as large corporations. Throughout, the authors asked: What makes the truly exceptional companies different from other companies? What separates General Electric, 3M, Merck, Wal-Mart, Hewlett-Packard, Walt Disney, and Philip Morris from their rivals? How, for example, did Procter & Gamble, which began life substantially behind rival Colgate, eventually prevail as the premier institution in its industry? How was Motorola able to move from a humble battery repair business into integrated circuits and cellular communications, while Zenith never became dominant in anything other than TVs? How did Boeing unseat McDonnell Douglas as the world's best commercial aircraft company -- what did Boeing have that McDonnell Douglas lacked? By answering such questions, Collins and Porras go beyond the incessant barrage of management buzzwords and fads of the day to discover timeless qualities that have consistently distinguished out-standing companies. They also provide inspiration to all executives and entrepreneurs by destroying the false but widely accepted idea that only charismatic visionary leaders can build visionary companies. Filled with hundreds of specific examples and organized into a coherent framework of practical concepts that can be applied by managers and entrepreneurs at all levels, Built to Last provides a master blueprint for building organizations that will prosper long into the twenty-first century and beyond.",
    category:     'business',
    link:         'https://www.amazon.ca/Built-Last-Successful-Visionary-Companies/dp/0060566108/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592515692&sr=8-1',
    photo:        "Built to Last.jpg"
  },
  {
    title:        'Creativity, Inc.: Overcoming the Unseen Forces That Stand in the Way of True Inspiration',
    description:  "Creativity, Inc. is a book for managers who want to lead their employees to new heights, a manual for anyone who strives for originality, and the first-ever, all-access trip into the nerve center of Pixar Animation—into the meetings, postmortems, and “Braintrust” sessions where some of the most successful films in history are made. It is, at heart, a book about how to build a creative culture—but it is also, as Pixar co-founder and president Ed Catmull writes, “an expression of the ideas that I believe make the best in us possible.” For nearly twenty years, Pixar has dominated the world of animation, producing such beloved films as the Toy Story trilogy, Monsters, Inc., Finding Nemo, The Incredibles, Up, and WALL-E, which have gone on to set box-office records and garner thirty Academy Awards. The joyousness of the storytelling, the inventive plots, the emotional authenticity: In some ways, Pixar movies are an object lesson in what creativity really is. Here, in this book, Catmull reveals the ideals and techniques that have made Pixar so widely admired—and so profitable. As a young man, Ed Catmull had a dream: to make the first computer-animated movie. He nurtured that dream as a Ph.D. student at the University of Utah, where many computer science pioneers got their start, and then forged a partnership with George Lucas that led, indirectly, to his founding Pixar with Steve Jobs and John Lasseter in 1986. Nine years later, Toy Story was released, changing animation forever. The essential ingredient in that movie’s success—and in the thirteen movies that followed—was the unique environment that Catmull and his colleagues built at Pixar, based on philosophies that protect the creative process and defy convention, such as: Give a good idea to a mediocre team, and they will screw it up. But give a mediocre idea to a great team, and they will either fix it or come up with something better. If you don’t strive to uncover what is unseen and understand its nature, you will be ill prepared to lead. It’s not the manager’s job to prevent risks. It’s the manager’s job to make it safe for others to take them. The cost of preventing errors is often far greater than the cost of fixing them.  A company’s communication structure should not mirror its organizational structure. Everybody should be able to talk to anybody. Do not assume that general agreement will lead to change—it takes substantial energy to move a group, even when all are on board.",
    category:     'business',
    link:         'https://www.amazon.ca/Creativity-Inc-Overcoming-Unseen-Inspiration/dp/0307361179/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592515844&sr=8-1',
    photo:        "Creativity, Inc.jpg"
  },
  {
    title:        'Principles',
    description:  "In 1975, Ray Dalio founded an investment firm, Bridgewater Associates, out of his two-bedroom apartment in New York City. Forty years later, Bridgewater has made more money for its clients than any other hedge fund in history and grown into the fifth most important private company in the United States, according to Fortune magazine. Dalio himself has been named to Time magazine’s list of the 100 most influential people in the world. Along the way, Dalio discovered a set of unique principles that have led to Bridgewater’s exceptionally effective culture, which he describes as “an idea meritocracy that strives to achieve meaningful work and meaningful relationships through radical transparency.” It is these principles, and not anything special about Dalio—who grew up an ordinary kid in a middle-class Long Island neighborhood—that he believes are the reason behind his success. In Principles, Dalio shares what he’s learned over the course of his remarkable career. He argues that life, management, economics, and investing can all be systemized into rules and understood like machines. The book’s hundreds of practical lessons, which are built around his cornerstones of “radical truth” and “radical transparency,” include Dalio laying out the most effective ways for individuals and organizations to make decisions, approach challenges, and build strong teams. He also describes the innovative tools the firm uses to bring an idea meritocracy to life, such as creating “baseball cards” for all employees that distill their strengths and weaknesses, and employing computerized decision-making systems to make believability-weighted decisions. While the book brims with novel ideas for organizations and institutions, Principles also offers a clear, straightforward approach to decision-making that Dalio believes anyone can apply, no matter what they’re seeking to achieve. Here, from a man who has been called both “the Steve Jobs of investing” and “the philosopher king of the financial universe” (CIO magazine), is a rare opportunity to gain proven advice unlike anything you’ll find in the conventional business press.",
    category:     'business',
    link:         'https://www.amazon.ca/Principles-Life-Work-Ray-Dalio/dp/1501124021/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592516021&sr=8-1',
    photo:        "Principles.jpg"
  },
  #################################### Investing ###########################################
  {
    title:        "Security Analysis",
    description:  "Rare is the opportunity to see, much less own, an original. But this unusual, carefully crafted reproduction of Benjamin Graham and David Dodd's immortal Security Analysis gives you that chance--to read and treasure a true classic--the book that gave birth to value investing. Continuously in print through five editions, for more than 60 years, and through nearly a million copies, the primer for many of America's most illustrious investors--and the wellspring of Graham and Dodd's Wall Street Immortality--Security Analysis is indisputably the most influential book on investing ever written. Still the investors' bible, it's as frequently consulted today as it was when it first appeared in 1934. Of course, over the years and over five editions, Security Analysis changed. Its language was modernized. New material was added. Metaphors and examples were brought up to date. In the light of changing times, these alterations were necessary and appropriate. But what of the original book? The very durability of this work arouses our curiosity. And what we discover when we return to the original is very simply a classic, a work whose uncompromising worth has not paled since it first saw the light of day in 1934. The original words of Benjamin Graham and David Dodd--put to paper not long after the disastrous Stock Market Crash of 1929--still have the mesmerizing qualities of rigorous honesty and diligent scrutiny, the same riveting power of disciplined thought and determined logic that gave the work its first distinction and began its illustrious career. The words you will read here are eloquent. Not only a financial genius and a man of high repute for honorable dealings, Graham was a man of letters invited to teach in the literature department at Columbia University (as well as in the economics and philosophy departments). But this reproduction is far more than a historical curiosity, an interesting object, and a delightful read. It presents the original Graham/Dodd method of investing--told in their own words as they first described it in the 1930s. What exactly is this method that has drawn such longterm devotion in the notably fickle reaches of Wall Street? Graham and Dodd were Wall Street's first bargain shoppers. In this book they first explain their methods for locating bonds and stocks which are selling well below the levels apparently justified by a careful analysis of the relevant facts. In this book, they tell you precisely how to find these undervalued securities and analyze those relevant facts. Are these methods still practical and usable today? The great fortunes created by value investors Warren Buffett, Mario Gabelli, John Neff, Michael Price, and John Bogle testify that they certainly are. In their preface to this book, Graham and Dodd write that they hope their work swill stand the test of the ever enigmatic future. There is no doubt that it has.",
    category:     'investing',
    link:         'https://www.amazon.ca/Benjamin-Graham/dp/0070244960/ref=sxts_sxwds-bia-wc-p13n1_0?cv_ct_cx=Security+Analysis&dchild=1&keywords=Security+Analysis&pd_rd_i=0070244960&pd_rd_r=e632655b-0679-4a20-ba9e-5b479000ebf3&pd_rd_w=Dhnfr&pd_rd_wg=aZq5V&pf_rd_p=5dc9bb73-73b1-4abd-a228-ac5c707beb7e&pf_rd_r=WF99QAPE62C92AKQ0RGA&psc=1&qid=1592516239&sr=1-1-70f7c15d-07d8-466a-b325-4be35d7258cc',
    photo:        "Security Analysis.jpg"
  },
  {
    title:        "Intelligent Investor: The Classic Text on Value Investing",
    description:  "The greatest investment advisor of the twentieth century, Benjamin Graham taught and inspired people worldwide. Graham's philosophy of value investing -- which shields investors from substantial error and teaches them to develop long-term strategies -- has made The Intelligent Investor the stock market bible ever since its original publication in 1949. Over the years, market developments have proven the wisdom of Graham's strategies. While preserving the integrity of Graham's original text, this revised edition includes updated commentary by noted financial journalist Jason Zweig, whose perspective incorporates the realities of today's market, draws parallels between Graham's examples and today's financial headlines, and gives readers a more thorough understanding of how to apply Graham's principles. Vital and indispensable, this HarperBusiness Essentials edition of The Intelligent Investor is the most important book you will ever read on how to reach your financial goals.",
    category:     'investing',
    link:         'https://www.amazon.ca/Intelligent-Investor-Classic-Value-Investing/dp/0060752610/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592516419&sr=1-1',
    photo:        "Intelligent Investor.jpg"
  },
  {
    title:        'Little Book of Common Sense Investing: The Only Way to Guarantee Your Fair Share of Stock Market Returns',
    description:  "The Little Book of Common Sense Investing is the classic guide to getting smart about the market. Legendary mutual fund  pioneer John C. Bogle reveals his key to getting more out of investing: low-cost index funds. Bogle describes the simplest and most effective investment strategy for building wealth over the long term: buy and hold, at very low cost, a mutual fund that tracks a broad stock market Index such as the S&P 500. While the stock market has tumbled and then soared since the first edition of Little Book of Common Sense was published in April 2007, Bogle’s investment principles have endured and served investors well.  This tenth anniversary edition includes updated data and new information but maintains the same long-term perspective as in its predecessor. Bogle has also added two new chapters designed to provide further guidance to investors:  one on asset allocation, the other on retirement investing. A portfolio focused on index funds is the only investment that effectively guarantees your fair share of stock market returns. This strategy is favored by Warren Buffett, who said this about Bogle: “If a statue is ever erected to honor the person who has done the most for American investors, the hands-down choice should be Jack Bogle. For decades, Jack has urged investors to invest in ultra-low-cost index funds. . . . Today, however, he has the satisfaction of knowing that he helped millions of investors realize far better returns on their savings than they otherwise would have earned. He is a hero to them and to me.” Bogle shows you how to make index investing work for you and help you achieve your financial goals, and finds support from some of the world's best financial minds: not only Warren Buffett, but Benjamin Graham, Paul Samuelson, Burton Malkiel, Yale’s David Swensen, Cliff Asness of AQR, and many others.",
    category:     'investing',
    link:         'https://www.amazon.ca/Little-Book-Common-Sense-Investing/dp/1119404509/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592516550&sr=1-1s',
    photo:        "Little Book of Common Sense Investing.jpg"
  },
  #################################### Trading ######################################
  {
    title:        'The Disciplined Trader: Developing Winning Attitudes',
    description:  "The classic book that introduced the investment industry to the concept of trading psychology. With rare insight based on his firsthand commodity trading experience, author Mark Douglas demonstrates how the mental matters that allow us function effectively in society are often psychological barriers in trading. After examining how we develop losing attitudes, this book prepares you for a thorough “mental housecleaning” of deeply rooted  thought processes. And then it shows the reader how to develop and apply attitudes and behaviors that transcend psychological obstacles and lead to success. The Disciplined Trader helps you join the elite few who have learned how to control their trading behavior (the few traders who consistently take the greatest percentage of profits out of the market) by developing a systematic, step-by-step approach to winning week after week, month after month.",
    category:     'trading',
    link:         'https://www.amazon.ca/Disciplined-Trader-Developing-Winning-Attitudes/dp/0132157578/ref=sr_1_1?dchild=1&keywords=The+Disciplined+Trader%3A+Developing+Winning+Attitudes&qid=1592516716&s=books&sr=1-1',
    photo:        "The Disciplined Trader.jpg"
  },
  {
    title:        'Market Wizards',
    description:  "How do the world's most successful traders amass tens, hundreds of millions of dollars a year? Are they masters of an occult knowledge, lucky winners in a random market lottery, natural-born virtuosi—Mozarts of the markets? In search of an answer, bestselling author Jack D. Schwager interviewed dozens of top traders across most financial markets. While their responses differed in the details, all of them could be boiled down to the same essential formula: solid methodology + proper mental attitude = trading success. In Market Wizards Schwager lets you hear, in their own words, what those super-traders had to say about their unprecedented successes, and he distils their responses down into a set of guiding principles you can use to become a trading star in your own right. ",
    category:     'trading',
    link:         'https://www.amazon.ca/Market-Wizards-Interviews-Top-Traders/dp/1592802974/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592516827&sr=1-1',
    photo:        "Market Wizards.jpg"
  },
  {
    title:        'Reminiscences of a Stock Operator',
    description:  "This investment classic now includes bonus chapters where Jesse Livermore reveals his investment strategies and market insights. Reminiscences of a Stock Operator is a fictionalized story based on the trading career of Jesse Livermore. It follows his journey from the age of 15 when he made his first $1,000 to becoming a Wall Street legend. See how he learned the ins and outs of trading the hard way while losing his fortune and then making it all back. Decades after its original publication, readers are still getting tremendous value from Livermore's experience. This updated edition includes bonus chapters that reveal the exact methods that Jessie Livermore used to make millions in the stock market. These chapters were based on a series of interviews conducted by top financial writer Richard D. Wyckoff and include extensive quotes from Livermore. Some of the topics he discusses include: how to identify what kinds of stocks to buy and when, the psychology of trading and how to get into a winning mindset, building a solid investment strategy that doesn't rely on trick or fads.",
    category:     'trading',
    link:         'https://www.amazon.ca/Market-Wizards-Interviews-Top-Traders/dp/1592802974/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1592516827&sr=1-1',
    photo:        "Reminiscences of a Stock Operator.jpg"
  }
  # {
  #   title:        Faker::Book.title,
  #   description:  Faker::GreekPhilosophers.quote,
  #   category:     category.sample,
  #   link:         'amazon.ca',
  #   photo:        "bookexample.jpg"
  # }
]
books_attributes.each { |params| Book.create!(params)}
